services:
  playlistsyncer:
    build:
      context: .
    container_name: playlistsyncer
    ports:
      - "8030:8000"
    dns:
      - "8.8.8.8"
    volumes:
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
      # Persistent Data (DB, History)
      - ./data:/app/data
      # Playlist sync cache
      - ./downloads/.sync:/app/downloads/.sync
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
