services:
  opusvault:
    build:
      context: ./backend
    container_name: opusvault
    ports:
      - "80:8000"
    dns:
      - "8.8.8.8"
    volumes:
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
      - ./playlists.json:/app/playlists.json
      - ./frontend:/app/frontend
      # Playlist sync cache
      - ./downloads/.sync:/app/downloads/.sync
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
